"""
audio_processor.py — Audio Post-Processing Module

This module handles the actual audio manipulation after the base TTS audio
has been generated by tts_engine.py. It uses the `pydub` library to modify:

  1. Pitch   — Frame-rate manipulation to shift pitch up/down by semitones
  2. Speed   — Playback speed adjustment via frame-rate trick + resampling
  3. Volume  — dB-based amplitude adjustment

Data Flow:
    input_mp3  →  load AudioSegment  →  apply pitch  →  apply speed
               →  apply volume  →  export as .wav  →  output_path

Connection to other modules:
    - Called by tts_engine.py after gTTS generates the base MP3
    - Receives VocalParameters from voice_modulator.py (via tts_engine.py)
    - Produces the final playable .wav file

Dependencies:
    - pydub (pip install pydub)
    - ffmpeg (system dependency — must be installed and on PATH)
"""

import logging
import os

from pydub import AudioSegment

from config import VocalParameters

logger = logging.getLogger(__name__)


def process_audio(
    input_path: str,
    vocal_params: VocalParameters,
    output_path: str,
) -> str:
    """
    Apply vocal modulation to an audio file and save the result.

    Args:
        input_path:   Path to the source audio file (MP3 from gTTS).
        vocal_params: The vocal modulation parameters to apply.
        output_path:  Desired path for the output .wav file.

    Returns:
        The absolute path to the generated .wav file.
    """
    logger.info(f"Processing audio: {input_path}")
    logger.info(
        f"Parameters — rate: {vocal_params.rate_factor}, "
        f"pitch: {vocal_params.pitch_semitones}st, "
        f"volume: {vocal_params.volume_db}dB"
    )

    # Load the source audio
    audio = AudioSegment.from_file(input_path)

    # Apply modulations in order: pitch → speed → volume
    audio = _apply_pitch(audio, vocal_params.pitch_semitones)
    audio = _apply_speed(audio, vocal_params.rate_factor)
    audio = _apply_volume(audio, vocal_params.volume_db)

    # Export as WAV
    audio.export(output_path, format="wav")

    logger.info(f"Audio saved to: {output_path}")
    return os.path.abspath(output_path)


def _apply_pitch(audio: AudioSegment, semitones: float) -> AudioSegment:
    """
    Shift the pitch of the audio by the given number of semitones.

    Technique: Modify the frame rate using the musical semitone formula:
        new_rate = original_rate × 2^(semitones / 12)

    Then re-set the frame rate back to the original to preserve duration.
    This effectively changes the perceived pitch without changing speed.

    Args:
        audio:     The AudioSegment to modify.
        semitones: Number of semitones to shift (positive = higher, negative = lower).

    Returns:
        Pitch-shifted AudioSegment.
    """
    if abs(semitones) < 0.1:
        return audio  # No meaningful pitch change

    # Calculate the new sample rate
    original_rate = audio.frame_rate
    new_rate = int(original_rate * (2.0 ** (semitones / 12.0)))

    # Resample: change the frame rate metadata (this shifts pitch AND speed)
    pitched = audio._spawn(audio.raw_data, overrides={"frame_rate": new_rate})

    # Re-set to original frame rate (this corrects the speed but keeps the pitch shift)
    pitched = pitched.set_frame_rate(original_rate)

    logger.debug(f"Pitch shifted by {semitones} semitones ({original_rate}Hz → {new_rate}Hz → {original_rate}Hz)")

    return pitched


def _apply_speed(audio: AudioSegment, rate_factor: float) -> AudioSegment:
    """
    Change the playback speed of the audio.

    For speed changes, we adjust the frame rate proportionally and then
    resample back. This changes the tempo without further pitch shift
    (pitch was already handled separately).

    Args:
        audio:       The AudioSegment to modify.
        rate_factor: Speed multiplier (1.0 = normal, >1 = faster, <1 = slower).

    Returns:
        Speed-adjusted AudioSegment.
    """
    if abs(rate_factor - 1.0) < 0.02:
        return audio  # Negligible speed change

    # Clamp rate factor to prevent extreme values
    rate_factor = max(0.5, min(2.0, rate_factor))

    original_rate = audio.frame_rate
    new_rate = int(original_rate * rate_factor)

    # Change frame rate (changes speed + pitch)
    sped = audio._spawn(audio.raw_data, overrides={"frame_rate": new_rate})

    # Reset to original frame rate (normalizes pitch back but keeps the new duration)
    sped = sped.set_frame_rate(original_rate)

    logger.debug(f"Speed adjusted by factor {rate_factor}")

    return sped


def _apply_volume(audio: AudioSegment, volume_db: float) -> AudioSegment:
    """
    Adjust the volume of the audio by the given dB amount.

    pydub makes this trivially simple — just add/subtract dB.

    Args:
        audio:     The AudioSegment to modify.
        volume_db: dB adjustment (positive = louder, negative = quieter).

    Returns:
        Volume-adjusted AudioSegment.
    """
    if abs(volume_db) < 0.1:
        return audio  # No meaningful volume change

    adjusted = audio + volume_db

    logger.debug(f"Volume adjusted by {volume_db} dB")

    return adjusted
